version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm start
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:11
    networks:
      - webnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/data:/docker-entrypoint-initdb.d
networks:
  webnet:
