---
name: 'Generate a release'

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  validate_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
